/*
 * action_dispatch.c -- calls Doom's action functions with the signature they actually have.
 *
 * Crispy Doom calls every state's action through a three-argument pointer, so that weapon actions and monster
 * actions can share one table. A CPU doesn't care, but WebAssembly checks the signature of an indirect call and
 * traps when it doesn't match, which is what killed the game the moment anything started thinking.
 *
 * So the two call sites (src/crispy_overrides/p_mobj.c and p_pspr.c) come through here instead, and this looks up
 * whether the function takes three arguments or one. The list is generated by tools/gen_action_table.py from
 * Crispy's own source, so it can't drift out of step by hand.
 */

#include "action_dispatch.h"
#include "action_table.h"

void tracedoom_call_action(void *action, void *mobj, void *player, void *psp)
{
    if (action == NULL)
        return;

    for (unsigned i = 0; i < sizeof(g_three_arg_actions) / sizeof(g_three_arg_actions[0]); i++)
    {
        if (g_three_arg_actions[i] == action)
        {
            ((void (*)(void *, void *, void *))action)(mobj, player, psp);
            return;
        }
    }
    /* everything else is a monster action, which takes only the thing it belongs to */
    ((void (*)(void *))action)(mobj);
}
