/* Generated by tools/gen_action_table.py -- the actions that take (mobj, player, psprite). */
void A_BFGsound(void *, void *, void *);
void A_CheckReload(void *, void *, void *);
void A_CloseShotgun2(void *, void *, void *);
void A_FireBFG(void *, void *, void *);
void A_FireCGun(void *, void *, void *);
void A_FireMissile(void *, void *, void *);
void A_FireOldBFG(void *, void *, void *);
void A_FirePistol(void *, void *, void *);
void A_FirePlasma(void *, void *, void *);
void A_FireShotgun(void *, void *, void *);
void A_FireShotgun2(void *, void *, void *);
void A_GunFlash(void *, void *, void *);
void A_Light0(void *, void *, void *);
void A_Light1(void *, void *, void *);
void A_Light2(void *, void *, void *);
void A_LoadShotgun2(void *, void *, void *);
void A_Lower(void *, void *, void *);
void A_OpenShotgun2(void *, void *, void *);
void A_Punch(void *, void *, void *);
void A_Raise(void *, void *, void *);
void A_RandomJump(void *, void *, void *);
void A_ReFire(void *, void *, void *);
void A_Saw(void *, void *, void *);
void A_WeaponReady(void *, void *, void *);

static void *const g_three_arg_actions[] = {
    (void *)A_BFGsound,
    (void *)A_CheckReload,
    (void *)A_CloseShotgun2,
    (void *)A_FireBFG,
    (void *)A_FireCGun,
    (void *)A_FireMissile,
    (void *)A_FireOldBFG,
    (void *)A_FirePistol,
    (void *)A_FirePlasma,
    (void *)A_FireShotgun,
    (void *)A_FireShotgun2,
    (void *)A_GunFlash,
    (void *)A_Light0,
    (void *)A_Light1,
    (void *)A_Light2,
    (void *)A_LoadShotgun2,
    (void *)A_Lower,
    (void *)A_OpenShotgun2,
    (void *)A_Punch,
    (void *)A_Raise,
    (void *)A_RandomJump,
    (void *)A_ReFire,
    (void *)A_Saw,
    (void *)A_WeaponReady,
};
