#!/usr/bin/env python3
"""
Lists Doom's action functions that take three arguments, for src/action_dispatch.c.

Crispy Doom calls every action through a three-argument pointer, which a CPU doesn't mind but WebAssembly rejects:
an indirect call has to match the function's real signature. src/action_dispatch.c calls each one properly, and this
works out which ones take three arguments. Re-run it if the Crispy Doom version in ../third_party changes.
"""
import re, glob, os, sys

src = os.path.join(os.path.dirname(__file__), '..', '..', 'third_party', 'crispy-doom-7.1', 'src', 'doom')
three = []
for path in sorted(glob.glob(os.path.join(src, '*.c'))):
    text = open(path, encoding='utf-8', errors='replace').read()
    for m in re.finditer(r'^\s*void\s+(A_[A-Za-z0-9_]+)\s*\(([^)]*)\)\s*\n?\{', text, re.M):
        name, params = m.group(1), m.group(2).strip()
        count = 0 if params in ('', 'void') else len([p for p in params.split(',') if p.strip()])
        if count == 3:
            three.append(name)

print('/* Generated by tools/gen_action_table.py -- the actions that take (mobj, player, psprite). */')
for name in sorted(three):
    print(f'void {name}(void *, void *, void *);')
print('\nstatic void *const g_three_arg_actions[] = {')
for name in sorted(three):
    print(f'    (void *){name},')
print('};')
